### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by BruceSaltzman** [playerofgames/logseq-mia-theme#1]
Installed and only light-mode available.

MacOS 12.3 (M1)
Version 0.6.4+nightly.20220322
Brave: Version 1.37.97 Chromium: 99.0.4844.74 (Official Build) beta (arm64)

**Comment by playerofgames** [comment]
Weird. I'm running 12.3 on an M1 Pro, and I've just checked the nightly and I have no problems with the following scenarios:

1. Logseq set to "System" theme mode, then change to dark more in macOS System Preferences->General
2. Cycling Logseq through modes with "t t"

So unfortunately, I'm unable to reproduce.

Unless…  maybe you are reporting that you only see one instance  of the theme in the "Themes" settings in Logseq… this is by design. The dark mode is enabled using Logseq preferences in that case (General->Theme mode). Some themes provide two separate themes, but miA uses the Logseq Theme mode setting (as does the default theme and some others).

**Comment by BruceSaltzman** [comment]
Thanks for checking into this. I did notice the one instance of your theme, rather than the usual light/dark provided by others. I was able to get it to work using your method. Nice job on this one. Thanks again.

------- Original Message -------

**Comment by playerofgames** [comment]
No worries, glad it is working. One advantage of having a single theme choice is that you then have the option to link it to the system light/dark mode more seamlessly.
