### ISSUE TITLE
Alignment of Bullet Points when using Bullet Threading in Headings

### ISSUE THREAD

**Issue by karkraeg** [playerofgames/logseq-mia-theme#13]
Hi, when uisng the https://github.com/pengx17/logseq-plugin-bullet-threading Plugin, the alignment of the bullet points when writing Headings look odd:

<img width="207" alt="Screenshot_2023-01-19_210222@2x" src="https://user-images.githubusercontent.com/8436596/213548176-e856e255-5fb4-4927-9396-e8863d3b5bfa.png">

Without the Plugin it's a little bit better but still somehow off:

<img width="210" alt="Screenshot_2023-01-19_210240@2x" src="https://user-images.githubusercontent.com/8436596/213548334-e4a448a1-adfd-4a20-9118-c33ffc566d95.png">

Can this be improved? Thanks!

**Comment by playerofgames** [comment]
The last time I looked at fixing it, I gave up. The miA theme behaviour was consistent with the other themes I looked at, including the default theme. IIRC the issue is that the bullet is a sibling of the element and doesn't 'know' that the following text has a larger line height (due to being a larger size).

Sorry!
