### ISSUE TITLE
css edits not picking up

### ISSUE THREAD

**Issue by wafflesatdawn** [playerofgames/logseq-mia-theme#20]
I really like how you transferred the iA Writer theme to Logseq; great work! I just tried to make minor edits on font weight, as prompted by the customization section in the readme, but found that they either aren't being picked up or I'm editing the wrong file: 

```
*:is(#main-content-container, #right-sidebar, .tippy-tooltip, .ls-card) *:is(.editor-inner .h3, .ls-block h3) {
	font-size: var(--content-h3-size, 110%);
	font-weight: var(--content-h3-font-weight, 500);
	font-style: var(--content-h3-font-style, italic);
}
```

It's supposed to be the mia_base.css right? Or would the mia_duo overwrite it even though it's not specifying font weight?

**Comment by playerofgames** [comment]
You don't need to edit mia_base to change the headings. You can override the variables in your custom.css file. For example,

```
:root {
  --content-h3-font-weight: bold;
}
```

makes H3 headings bold. Changing the weight to 500 has no effect for mia duo because that weight is not available for the font, so the renderer chooses the next closest (normal).

Hope that helps!

**Comment by wafflesatdawn** [comment]
Ah, I thought the setting was more like a display option rather than accessing different font weights. Thanks
