### ISSUE TITLE
Removing 1px bottom border from links?

### ISSUE THREAD

**Issue by blu-mag** [playerofgames/logseq-mia-theme#21]
Just found this theme and really loving it so far! Not an issue so much as a question. Is there a way to not display this 1px bottom border on links? I find it a little distracting since the link text is already underlined:

<img width="184" alt="image" src="https://github.com/playerofgames/logseq-mia-theme/assets/109391238/2494ab3c-5e80-493d-aaf9-55f07efa792c">

My front-end web skills are a little rusty, but I looked through the .CSS for a bottom-border property attached to link/<a> elements, but I came up empty. I did find this in mia_sans.css, but that doesn't seem to actually be being applied:

```
a.external-link {
	text-decoration: underline;
	border: none;
```

I went ahead and added that to my custom.css but changed it to `border: none !important;` and that seemed to do the trick.

So it’s display how I’d like now, but I’m wondering if it’s a bug that the border is showing, and if my fix might have some unintended side effects, or if the border is intended.

Thanks!

**Comment by playerofgames** [comment]
Thanks for your feedback, I'm glad you like the theme!

I wonder if some other plugin is changing the link rendering, like the plugin that is fetching the site favicon? 

Logseq default styling is _not_ to use text-underline, but to use a border bottom instead. I overrode that in the proportional font mia variants because I thought it looked better. I suspect a plugin is overriding the external link style too (but perhaps not turning off the bottom border). Which plugin are you using for this?

**Comment by blu-mag** [comment]
So, after some more poking around, I saw it wasn’t happening on all my synced computers. I went ahead and disabled all my plugins, totally cleared custom.css, and re-enabled them all one by one. I thought that the site favicon plugin might be the culprit, but as it turns out, after re-enabling, no more bottom-border. It seems okay now—maybe it was machine specific, but I’ll keep an eye out and let you know if it comes back!
