### ISSUE TITLE
arrow symbol rendering

### ISSUE THREAD

**Issue by crendl** [playerofgames/logseq-mia-theme#8]
hi again,

using the standard theme in logseq, `->` will be rendered as an arrow &rarr; 
with miA, this not happening. 

any reason for this? is this due to a certain version of markdown implemented? 

regards

**Comment by playerofgames** [comment]
This is due to something called _contextual ligatures_ in the font used by the default Logseq theme. The _iA Writer_ fonts do not contain this contextual ligature.

If you want to use the default Logseq font with the _miA_ theme, which is called _Inter_, you can add the following to your `custom.css` file:

```
:root {
  --content-font-family: "Inter";
}
```

Of course, this may remove one of the reasons for choosing the them in the first place! (No need to install the font, as it is included in the base Logseq CSS.)

If you are looking for a monospace font with this sort of ligature, you might like [Fira Code](https://github.com/tonsky/FiraCode) which you could install and use with a similar CSS override as above.

**Comment by crendl** [comment]
thanks very much martin for taking your time to explain it to me also giving me some options, it is much appreciated!

edit: i opted for the possibility to add custom commands in logseq and stick with san francisco:
`:commands 
 [ ["arrr" "🠆"], ["arrl" "🠄"]]
 `
